apiVersion: v1
kind: Service
metadata:
  name: webssh
  namespace: webssh
spec:
  selector:
    app: webssh
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30022
  type: NodePort
