version: "3.9"

services:
  neo4j:
    network_mode: "host"
    restart: on-failure
    image: "neo4j:4.4.9-community"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - /dev/bigboy/n4j/plugins:/plugins
      - /dev/bigboy/n4j/data:/data
