kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-storage-class
  namespace: kafka
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-2
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-3
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-4
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-5
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-6
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-7
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-8
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka-8
