apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calcoulomb
  namespace: calcoulomb
subjects:
- kind: ServiceAccount
  name: calcoulomb
  namespace: calcoulomb
roleRef:
  kind: ClusterRole
  name: cluster-admin  # You can change this to a more specific role if needed
  apiGroup: rbac.authorization.k8s.io
