kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-storage-class
  namespace: kafka
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-world-pv
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-world-pvc
  namespace: kafka
spec:
  storageClassName: kafka-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
