apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: minecraft
spec:
  selector:
    app: sevtech
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
    nodePort: 30093
  type: NodePort
