kind: Service
apiVersion: v1
metadata:
  labels:
    app: helloworld
  name: helloworld-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: helloworld
