apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: bsc
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: node
          image: ghcr.io/minish144/bsc-full-node:latest
          imagePullPolicy: Always
          args:
            - --config
            - "/bsc/config.toml"
            - --datadir
            - "/bsc/node"
            - --cache
            - "8000"
            - --rpc.allow-unprotected-txs
            - --syncmode
            - "full"
            - --tries-verify-mode
            - "none"
            - --diffblock
            - "5000"
            - --rpc.txfeecap
            - "0"
            - --rpc.gascap
            - "0"
            - --http
            - --http.vhosts
            - "*"
            - --http.corsdomain
            - "*"
            - --pruneancient
            - --history.transactions
            - "0"
            - --db.engine
            - "pebble"
            - --ws
            - --ws.origins
            - "*"
            - --block-amount-reserved
            - "1024"
            - --http.addr
            - "0.0.0.0"
            - --http.port
            - "8545"
            - --ws.addr
            - "0.0.0.0"
            - --ws.port
            - "8546"
            - --discovery.port
            - "30311"
          resources:
            requests:
              cpu: 4
              memory: 16Gi
            limits:
              cpu: 16
              memory: 32Gi
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 30311
          volumeMounts:
            - name: config
              mountPath: /bsc/config.toml
            - name: genesis
              mountPath: /bsc/genesis.json
            - name: node
              mountPath: /bsc/node
          securityContext:
            privileged: false
            runAsNonRoot: false
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: config
          hostPath:
            path: /dev/bigboy/bsc/config.toml
            type: File
        - name: genesis
          hostPath:
            path: /dev/bigboy/bsc/genesis.json
            type: File
        - name: node
          hostPath:
            path: /dev/bigboy/bsc/node
            type: Directory
