apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: peering-udp
  namespace: bsc
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pr-udp
      port: 30311
      protocol: UDP
      targetPort: 30311
  selector:
    app: node
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: peering-tcp
  namespace: bsc
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pr-tcp
      port: 30311
      protocol: TCP
      targetPort: 30311
  selector:
    app: node
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: node
  name: rpc-http
  namespace: bsc
spec:
  ports:
    - port: 8545
      targetPort: 8545
      protocol: TCP
  selector:
    app: node
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: node
  name: rpc-wss
  namespace: bsc
spec:
  ports:
    - port: 8546
      targetPort: 8546
      protocol: TCP
  selector:
    app: node
