apiVersion: v1
kind: Service
metadata:
  name: p2p
  labels:
    app: node
  namespace: bsc
spec:
  selector:
    app: node
  ports:
    - protocol: UDP
      port: 30311
      targetPort: 30311
      nodePort: 30311
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-http
  labels:
    app: node
  namespace: bsc
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30045
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-ws
  labels:
    app: node
  namespace: bsc
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 8546
      targetPort: 8546
      nodePort: 30046
  type: NodePort
