kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sevtech-storage-class
  namespace: minecraft
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sevtech-world-pv
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sevtech-world
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sevtech-world-pvc
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sevtech-backups-pv
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sevtech-backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sevtech-backups-pvc
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sevtech-cfg-pv
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sevtech-cfg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sevtech-cfg-pvc
  namespace: minecraft
spec:
  storageClassName: sevtech-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
