apiVersion: apps/v1
kind: Deployment
metadata:
  name: sevtech-deployment
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sevtech
  template:
    metadata:
      labels:
        app: sevtech
    spec:
      containers:
        - name: sevtech
          image: elmonitoboy/sevtech-docker:3.2.3
          ports:
            - containerPort: 25565
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 8Gi
              cpu: 2.5
          volumeMounts:
            - name: world-volume
              mountPath: /minecraft/world
            - name: backups-volume
              mountPath: /minecraft/backups
      volumes:
        - name: world-volume
          persistentVolumeClaim:
            claimName: sevtech-world-pvc
        - name: backups-volume
          persistentVolumeClaim:
            claimName: sevtech-backups-pvc
