apiVersion: v1
kind: Service
metadata:
  name: sevtech-service
  namespace: minecraft
spec:
  selector:
    app: sevtech
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 32556
  type: NodePort
