apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wireguard-user-access
  namespace: wireguard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wireguard
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: wireguard-ns-group
