kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wireguard-storage-class
  namespace: wireguard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wireguard
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wireguard-storage-class
  local:
    path: /mnt/wireguard
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${VOLUME_NODE_NAME}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wireguard
  namespace: wireguard
spec:
  storageClassName: wireguard-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
