apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      hostNetwork: true
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: wg-config
            mountPath: /config
          - name: host-volumes
            mountPath: /lib/modules
        ports:
        - containerPort: 31820
          protocol: UDP
        resources:
          requests:
            memory: 64Mi
            cpu: 0.1
          limits:
            memory: 256Mi
            cpu: 0.3
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wireguard-config-pvc
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory

