kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: wireguard
  name: wireguard-service
  namespace: wireguard
spec:
  type: NodePort
  ports:
  - port: ${SERVERPORT}
    nodePort: ${SERVERPORT}
    protocol: UDP
    targetPort: ${SERVERPORT}
  selector:
    app: wireguard
