apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-ui-db-pv
  namespace: wireguard
spec:
  storageClassName: wireguard-storage-class
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/wireguard-ui-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-ui-db-pvc
  namespace: wireguard
spec:
  storageClassName: wireguard-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

