apiVersion: v1
kind: Service
metadata:
  name: wireguard-ui-service
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30005
