name: build

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: buildx context
        run: docker context create builders

      - name: set up buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Minish144
          password: ${{ secrets.PAT }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bsc-node/
          push: true
          tags: ghcr.io/minish144/bsc-full-node
